### ISSUE TITLE
The extension is no longer able to create/update index

### ISSUE THREAD

**Issue by jsfr** [mikkeloscar/ku-purchase-search#1]
After an update on https://intranet.ku.dk/indkoeb/finddinbestiller/Sider/Finddinbestiller.aspx the extension is no longer able to crawl and update the index

**Comment by jsfr** [comment]
Closing as not expecting a fix

**Comment by mikkeloscar** [comment]
Hehe, håber ikke du har siddet og ventet på et fix siden :)

Den ændring de lavede dengang var ikke bare dårligere end det der var, men utrolig besværlig at crawle, så jeg opgav det på det tidspunkt.

Har så aldrig opdaget denne issue før jeg fik en besked om at den var lukket.

**Comment by jsfr** [comment]
Nej nej.. jeg ryddede bare op i gamle issues da de lå og rodede ;)
